### ISSUE TITLE
grammar [ p = 'a' p 'a' | 'a' ] do not parse properly

### ISSUE THREAD

**Issue by druxa** [alexwarth/ometa-js#13]
```
ometa L  {
  p = 'a' p:x 'a' -> (x+1) | 'a' -> 0
}

alert(L.matchAll("aaa", 'p')) // 1 - ok
alert(L.matchAll("aaaaa", 'p')) // 1 - wrong!
alert(L.matchAll("aaaaaaa", 'p')) // 3 - ok
alert(L.matchAll("aaaaaaaaa", 'p')) // 1 - wrong!
alert(L.matchAll("aaaaaaaaaaa", 'p')) // 3 - wrong!
alert(L.matchAll("aaaaaaaaaaaaa", 'p')) // 5 - wrong!
alert(L.matchAll("aaaaaaaaaaaaaaa", 'p')) // 7 - ok
```

**Comment by alexwarth** [comment]
Hi Druxa,

What's going on here is that "matchAll" is a really bad name -- what it really means is "apply this rule to this string of characters, and succeed even if there are characters left after the rule is satisfied." I've wanted to change the semantics of matchAll to require the "end" of the string, but I haven't gotten around to it yet because I don't want to break any existing grammars.

Anyway, here's a version of your code that does what you expected:

ometa L  {
  p = 'a' p:x 'a' -> (x+1) | 'a' -> 0,
  start = p:ans end -> ans
}

L.matchAll("aaa", 'start')
L.matchAll("aaaaa", 'start')
L.matchAll("aaaaaaa", 'start')
L.matchAll("aaaaaaaaa", 'start')
L.matchAll("aaaaaaaaaaa", 'start')
L.matchAll("aaaaaaaaaaaaa", 'start')
L.matchAll("aaaaaaaaaaaaaaa", 'start')

**Comment by druxa** [comment]
Hmm... Now I get "match failed" in

```
L.matchAll("aaaaa", 'start')
L.matchAll("aaaaaaaaa", 'start')
...
```

which is still wrong, or?.. I'm using http://tinlizzie.org/ometa-js/#OMeta_Tutorial, mb it is not the latest version?

**Comment by alexwarth** [comment]
Nothing's wrong with that -- it's actually the expected behavior. OMeta is based on Parsing Expression Grammars (not Context-Free Grammars) and there are some unambiguous grammars that PEGs cannot recognize. If you really want to understand this, you should read Bryan Ford's papers, but for now I'll leave you with an exceprt from the Wikipedia page on PEGs:

"""
Expressive power
Packrat parsers cannot recognize some unambiguous grammars, such as the following (example taken from[10])
S ← 'x' S 'x' | 'x'
In fact, neither LL(k) nor LR(k) parsing algorithms are capable of recognizing this example.
"""

This is your grammar, it's it? :)

Cheers,
Alex

**Comment by druxa** [comment]
Got it. The first impression on OMeta was it could parse anything whatsoever =)

**Comment by alexwarth** [comment]
I'm not saying it can't -- you just have to ask it nicely :)

**Comment by veged** [comment]
Alex, you're just joking or really is a way to ask it nicely for parse `S ← 'x' S 'x' | 'x'`?

**Comment by ehsanul** [comment]
Interesting...

```
ometa L  {
  p = 'a' p:x 'a' -> ['a', x, 'a'] | 'a' -> 'a',
  start = p:x end -> x
}

L.matchAll("aaa", 'start')
// [a, a, a]

L.matchAll("aaaaa", 'start')
// match failed

L.matchAll("aaaaaaa", 'start')
// [a, [a, [a, a, a], a], a]

L.matchAll("aaaaaaaaaaaaaaa", 'start')
// [a, [a, [a, [a, [a, [a, [a, a, a], a], a], a], a], a], a]
```

I don't really understand why "aaaaaaa" works, but "aaaaa" doesn't. I'll have to look at Ford's paper, but not sure that'll help me to understand this.
